# Generated by Django 5.2.3 on 2025-06-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_create_date_product_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('varation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
