# Generated by Django 5.2.3 on 2025-06-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_varations_cartitem_variations'),
        ('store', '0003_varation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varation',
            new_name='Variation',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varation_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='varation_value',
            new_name='variation_value',
        ),
    ]
