# Generated by Django 5.2.3 on 2025-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0003_varation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varations',
            field=models.ManyToManyField(blank=True, to='store.varation'),
        ),
    ]
